### ISSUE TITLE
Integrate React_on_Rails

### ISSUE THREAD

**Issue by nma** [julianguyen/ifme#579]
## WIP Branch
https://github.com/nma/ifme/tree/react-moment-dashboards-rebase

## Todo List
- [x] Merge in master
- [x] Get all specs passing in merged branch
- [x] Create PR (#580)
- [x] Pass Rubocop checks / Code Climate checks
- [x] Test Heroku Deployment on separate account
- [ ] Write Documentation

## Rendering React Component
![chartformoments](https://user-images.githubusercontent.com/845531/29738343-82b43e42-89ee-11e7-8538-30a879450c18.png)

**Comment by baohouse** [comment]
Going to close this and have the documentation task reside within #613
